### ISSUE TITLE
Some TLS notebooks are outdated

### ISSUE THREAD

**Issue by cs-862** [secdev/scapy#3073]
#### Brief description

The notebooks 1 to 3 in `doc/notebooks/tls` are not working properly. Below more details, where every notebook fails:

**`notebook1_x509.ipynb`** (first error in [17]):
Error message: `AttributeError: 'PrivKeyRSA' object has no attribute 'key'`

**`notebook2_tls_protected`** (first error in [4]):
Error message `AttributeError: certs`

**`notebook3_tls_compromised`** (first error in [3]):
Error message `AttributeError: 'TLS_RSA_WITH_AES_128_CBC_SHA' object has no attribute '_key_block_len_v1_0'`

**`notebook4_tls13`** (first errror in [6]):
Error message `TypeError: 'NoneType' object is not callable`

#### Environment

-   Scapy version: `2.4.4.dev275`
-   Python version: `3.9.1`
-   Operating System: `ManjaroLinux 20.2.1`

#### How to reproduce

Open the `.ipynb`-files mentioned above with `jupyter notebook` and run it by restarting the kernel.

As I am a new scapy-user I am not sure, if there are problems with the TLS layer or if the simply the notebooks must be updated.

**Comment by gpotter2** [comment]
I couldn't replicate any of those issues. Do you have cryptography installed?

**Comment by cs-862** [comment]
I thougth so, but probably there was something wrong. Reinstalling cryptography solved most of the issues.

Notebook 1, 2, and 3 are fine.

In notebook 5 I got the Warning "Unknown cipher suite 1049 from ServerHello" running the notebook as it is.
After uncommenting the fifth input (were the keys are set and computed), I have a key error on 'secp256r1'.

I am still doing something wrong?

**Comment by gpotter2** [comment]
Those are probably regressions. I'll check them out, thanks for the report !

**Comment by guedou** [comment]
This is a regression introduced in 3e131e2dec97277982a379784dc07f378c5c047f:

Before `record4_str` was decoded as:
```
###[ TLS ]### 
  type      = handshake
  version   = TLS 1.0
  len       = 115    [deciphered_len= 115]
  iv        = b''
  \msg       \
   |###[ TLS 1.3 Handshake - Server Hello ]### 
   |  msgtype   = server_hello
   |  msglen    = 111
   |  version   = TLS 1.3-d18
   |  random_bytes= 96ff693075d8465651a9c28773f5496542206ba390199b9c997545d9a1266615
   |  cipher    = TLS_AES_128_GCM_SHA256
   |  extlen    = 73
   |  \ext       \
   |   |###[ TLS Extension - Key Share (for ServerHello) ]### 
   |   |  type      = key_share
   |   |  len       = 69
   |   |  \server_share\
   |   |   |###[ Key Share Entry ]### 
   |   |   |  group     = secp256r1
   |   |   |  kxlen     = 65
   |   |   |  key_exchange= '\x04\x8aM\t\xcd\xe5\x8d\xbc\x04\x19U\xb9\xa4\x1aC\xc1im\xc5B\x9f\xfa\x96\xf9\xcd\x19J\x86:\xc7\x82\xf1\x81Y\xf0r\xb4\xf6\x10!]\x86@}\xd76\x8buJ\xb2\xe6O,\x1b?\x9dE|&N+\x17\x81\xa3k'
  mac       = b''
  pad       = b''
  padlen    = None
```

I am unsure that it is worth fixing the code as the notebook examples are based on a TLS 1.3 early draft.
