### ISSUE TITLE
Scapy pipes seem broken

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#3264]
According to `git bisect`, the following code does not work since 9a9853f39f091e781321c92b574ec612e1f62ddb

```
from scapy.all import *

clf = CLIFeeder()
pe = PipeEngine(clf)
pe.start()
clf.send("Hello Scapy!")
ijs = InjectSink()
clf > ijs
pe.stop()
```

It currently fails with:
```
ERROR: piping from ObjectPipe failed: 'InjectSink' object has no attribute 's'
Traceback (most recent call last):
  File "/Users/guedou/Projects/Scapy/scapy.git/scapy/pipetool.py", line 128, in run
    fd.deliver()
  File "/Users/guedou/Projects/Scapy/scapy.git/scapy/pipetool.py", line 425, in deliver
    self._send(msg)
  File "/Users/guedou/Projects/Scapy/scapy.git/scapy/pipetool.py", line 269, in _send
    s.push(msg)
  File "/Users/guedou/Projects/Scapy/scapy.git/scapy/scapypipes.py", line 129, in push
    self.s.send(msg)
AttributeError: 'InjectSink' object has no attribute 's'
```

**Comment by gpotter2** [comment]
I believe that the bissect is wrong: this issue happens on v2.4.0 :/

**Comment by KhazAkar** [comment]
Quick check for you @guedou - in scapypipes.py, in line 148, under it, add self.start()
Will this work for you?

**Comment by KhazAkar** [comment]
Hi again,
This sample.can be also saved from editing, by simply invoking ijs.start() :)

**Comment by guedou** [comment]
Well, I managed to make this snippet work after modifying it. Here, we need to identify the regression and fix it (if relevant).

**Comment by gpotter2** [comment]
I would argue that current behavior is expected: the snippet should be
```python
clf = CLIFeeder()
pe = PipeEngine(clf)
ijs = InjectSink()
clf > ijs
pe.add(clf)
pe.start()
clf.send(b"Hello Scapy!")
pe.stop()
```

e.g.
- add the sources/sinks before starting the engine, so that they are started at the same time
- you forgot to add the sources to the engine
