### PR TITLE
Use ClassVar for Packet.fields_desc type hint

### LINKED ISSUE #4991: Type Hints: Use `typing.ClassVar` for `Packet.fields_desc`
`Packet.fields_desc` is currently hinted with `# type: List[AnyField]`, which results in a tooling conflict with [RUFF012](https://docs.astral.sh/ruff/rules/mutable-class-default/).

Suggestion - import `typing.ClassVar` and apply the type hint to `fields_desc` like so: `# type: ClassVar[List[AnyField]]`

### PR DESCRIPTION
**Pull request by T3pp31**
## Summary
- import `ClassVar` in `scapy.packet`
- annotate `Packet.fields_desc` as `ClassVar[List[AnyField]]`
- keep runtime behavior unchanged

Closes #4991

## Checks
- `python3 -m py_compile scapy/packet.py`
- `git diff --check`

Not run locally:
- `tox -e flake8` (`tox` resolves to a broken pyenv-win shim; `python3 -m tox` is not installed)
- `tox -e mypy` (same tox issue)
- `python3 -m ruff check --select RUF012 scapy/packet.py` (`ruff` is not installed)

### CODE REVIEW

**Comment by T3pp31** [comment]
CI note: after adding the required `AI-Assisted` commit trailer, the commit validity check is passing.

The remaining failing check is `ubuntu-latest pypy3.11 root -K scanner`. Its log shows `TypeError: test_am() missing 1 required positional argument: 'mock_sniff'` while running on PyPy 7.3.22. This appears unrelated to this PR's `scapy/packet.py` type-comment-only change and looks like the known PyPy 7.3.22 regression tracked in #4995.

Relevant checks for this change are passing, including `Code health check`, `Type hints check`, `CodeQL`, and `Codacy Static Code Analysis`.
