### ISSUE TITLE
contrib/pnio fails after #3296

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#3315]
### Brief description

A unit test introduced in #3296 fails on Mac OSX:

```
###(049)=[failed] AlarmCRBlockReq with transport

>>> bytes(AlarmCRBlockReq(AlarmCRProperties_Transport=1)) == bytearray.fromhex('010300160100000108004000000000010003000300c8c000a000')
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "scapy/packet.py", line 555, in __str__
    return self.build()
  File "scapy/packet.py", line 695, in build
    p = self.do_build()
  File "scapy/packet.py", line 680, in do_build
    return self.post_build(pkt, pay)
  File "scapy/contrib/pnio_rpc.py", line 889, in post_build
    print("p[:8]={}".format(bytes(p[:8]).hex()))
AttributeError: 'str' object has no attribute 'hex'



UTscapy ended with error code 1
ERROR: InvocationError for command /usr/bin/sudo -E .tox/py27-bsd_root/bin/python -m coverage run -m scapy.tools.UTscapy -c test/configs/bsd.utsc -K manufdb -K tshark -K tun -K tap (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py27-bsd_non_root: commands failed
ERROR:   py27-bsd_root: commands failed
Error: Process completed with exit code 1.
```

https://github.com/secdev/scapy/pull/3309/checks?check_run_id=3218218378

### Scapy version

2.4.5

### Python version

2.7

### Operating system

macos-latest 2.7 both

### How to reproduce

https://github.com/secdev/scapy/pull/3309/checks?check_run_id=3218218378

**Comment by polybassa** [comment]
Also failing on windows: https://ci.appveyor.com/project/secdev/scapy/builds/40215117/job/ylfdhqsvhumalxx9
```
PNIO RPC layer test campaign
-- Run at 07:08:44 from [test\contrib\pnio_rpc.uts] by UTscapy in 0.233999967575
 -> Passed=61
 -> Failed=1
######
## Check AlarmCRBlockReq
######
###(049)=[failed] AlarmCRBlockReq with transport
>>> bytes(AlarmCRBlockReq(AlarmCRProperties_Transport=1)) == bytearray.fromhex('010300160100000108004000000000010003000300c8c000a000')
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "scapy\packet.py", line 555, in __str__
    return self.build()
  File "scapy\packet.py", line 695, in build
    p = self.do_build()
  File "scapy\packet.py", line 680, in do_build
    return self.post_build(pkt, pay)
  File "scapy\contrib\pnio_rpc.py", line 889, in post_build
    print("p[:8]={}".format(bytes(p[:8]).hex()))
AttributeError: 'str' object has no attribute 'hex'

```

**Comment by gpotter2** [comment]
This was fixed in https://github.com/secdev/scapy/commit/513f2dacaeefcc45c01fabce70f70d228ee5a194
