### ISSUE TITLE
scapy 2.4.2 & Windows 10 => ImportError: cannot import name 'NPCAP_PATH'

### ISSUE THREAD

**Issue by daniel-leicht** [secdev/scapy#1819]
#### Brief description
Regression bug:
scapy 2.4.2 & Windows 10 => ImportError: cannot import name 'NPCAP_PATH'

This happens only in scapy 2.4.2 & 2.4.1, when downgrading back to 2.4.0 the problem disappears.

#### Environment

-   Scapy version: 2.4.2
-   Python version: 3.6.3 x64
-   Operating System: Windows 10
-   Winpcap 4.1.3

#### How to reproduce

Run this simple script:
```
from scapy.layers.inet import Ether, IP, TCP, ICMP
from scapy.sendrecv import send, sr
from random import randint

ip_pdu = IP()
ip_pdu.ttl = 48
ip_pdu.flags = 0x0000
ip_pdu.tos = 0xa0
ip_pdu.dst = '192.168.43.177'
ip_pdu.id = randint(1, 64000)

sr(ip_pdu / ICMP())
```
#### Actual result

When installing scapy 2.4.2 or 2.4.1 via pip install, the following exception pops:
```
Traceback (most recent call last):
  File "C:/Projects/ActiveFingerprintProbe/main.py", line 43, in <module>
    from scapy.layers.inet import Ether, IP, TCP, ICMP
  File "C:\Python36\lib\site-packages\scapy\layers\inet.py", line 25, in <module>
    from scapy.layers.l2 import Ether, Dot3, getmacbyip, CookedLinux, GRE, SNAP, \
  File "C:\Python36\lib\site-packages\scapy\layers\l2.py", line 17, in <module>
    from scapy.ansmachine import AnsweringMachine
  File "C:\Python36\lib\site-packages\scapy\ansmachine.py", line 16, in <module>
    from scapy.sendrecv import send, sniff
  File "C:\Python36\lib\site-packages\scapy\sendrecv.py", line 33, in <module>
    import scapy.route  # noqa: F401
  File "C:\Python36\lib\site-packages\scapy\route.py", line 194, in <module>
    conf.route = Route()
  File "C:\Python36\lib\site-packages\scapy\route.py", line 27, in __init__
    self.resync()
  File "C:\Python36\lib\site-packages\scapy\route.py", line 33, in resync
    from scapy.arch import read_routes
  File "C:\Python36\lib\site-packages\scapy\arch\__init__.py", line 67, in <module>
    from scapy.arch.windows import *  # noqa F403
  File "C:\Python36\lib\site-packages\scapy\arch\windows\__init__.py", line 56, in <module>
    from scapy.arch.pcapdnet import NPCAP_PATH, get_if_raw_addr, \
ImportError: cannot import name 'NPCAP_PATH'
```
#### Expected result

If I uninstall scapy and reinstall 2.4.0 with pip, everything works:
```
Begin emission:
..Finished sending 1 packets.
.*
Received 4 packets, got 1 answers, remaining 0 packets
```

#### Related resources

I tried to debug the issue a bit and it seems that in pcapdnet.py in line 102 the conf.use_winpcapy is True and the if condition is satisfied. So I'm not sure why the import fails.

**Comment by gpotter2** [comment]
This is a known bug :/ It is fixed in https://github.com/secdev/scapy/pull/1759

We should have it merged soon, it has a quite big windows overhaul (speed up booting x3...)

**Comment by daniel-leicht** [comment]
> This is a known bug :/ It is fixed in #1759
I tried looking first, but didn't find anything about this issue.
> 
> We should have it merged soon, it has a quite big windows overhaul (speed up booting x3...)
Thanks, I'll be waiting for it to get merged.

**Comment by gpotter2** [comment]
Hi, could you please retry against master ?

The PR has been merged

**Comment by daniel-leicht** [comment]
> Hi, could you please retry against master ?
> 
> The PR has been merged

I tried installing from master by cloning and running "setup.py install", but I get the following error when importing (this line works on 2.4.2 & 2.4.0 from pip):

`
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
from scapy.layers.inet import Ether, IP, TCP, ICMP
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2018.2.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python36\lib\site-packages\scapy-2.4.2.dev107-py3.6.egg\scapy\layers\inet.py", line 25, in <module>
    from scapy.layers.l2 import Ether, Dot3, getmacbyip, CookedLinux, GRE, SNAP, \
  File "C:\Program Files\JetBrains\PyCharm 2018.2.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python36\lib\site-packages\scapy-2.4.2.dev107-py3.6.egg\scapy\layers\l2.py", line 17, in <module>
    from scapy.ansmachine import AnsweringMachine
  File "C:\Program Files\JetBrains\PyCharm 2018.2.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python36\lib\site-packages\scapy-2.4.2.dev107-py3.6.egg\scapy\ansmachine.py", line 16, in <module>
    from scapy.sendrecv import send, sniff
  File "C:\Program Files\JetBrains\PyCharm 2018.2.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python36\lib\site-packages\scapy-2.4.2.dev107-py3.6.egg\scapy\sendrecv.py", line 35, in <module>
    import scapy.route  # noqa: F401
  File "C:\Program Files\JetBrains\PyCharm 2018.2.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python36\lib\site-packages\scapy-2.4.2.dev107-py3.6.egg\scapy\route.py", line 194, in <module>
    conf.route = Route()
  File "C:\Python36\lib\site-packages\scapy-2.4.2.dev107-py3.6.egg\scapy\route.py", line 27, in __init__
    self.resync()
  File "C:\Python36\lib\site-packages\scapy-2.4.2.dev107-py3.6.egg\scapy\route.py", line 33, in resync
    from scapy.arch import read_routes
  File "C:\Program Files\JetBrains\PyCharm 2018.2.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python36\lib\site-packages\scapy-2.4.2.dev107-py3.6.egg\scapy\arch\__init__.py", line 68, in <module>
    from scapy.arch.windows.native import *  # noqa F403
  File "C:\Program Files\JetBrains\PyCharm 2018.2.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python36\lib\site-packages\scapy-2.4.2.dev107-py3.6.egg\scapy\arch\windows\native.py", line 58, in <module>
    from scapy.layers.inet import IP
ImportError: cannot import name 'IP'
`

**Comment by gpotter2** [comment]
Thanks for that ! That’s a different issue but nonetheless important !

**Comment by gpotter2** [comment]
Fixed in https://github.com/secdev/scapy/pull/1833

**Comment by aminought** [comment]
Sorry, but it seems that problem was not solved. I've tried to clone master branch, install via `python setup.py install`, type `from scapy.all import sniff` and finally received the same error.

**Comment by gpotter2** [comment]
Hi @aminought Please retry [**using the GitHub dev version**](https://github.com/secdev/scapy/archive/master.zip)

**Comment by scottie** [comment]
same here, confirmed not working on windows 10

**Comment by gpotter2** [comment]
Hi @scottie Please retry [**using the GitHub dev version**](https://github.com/secdev/scapy/archive/master.zip)
