### ISSUE TITLE
TypeError: copy() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by lalten** [secdev/scapy#3434]
### Brief description

I'm in the progress of upgrading from Scapy 2.4.4 to 2.4.5.
In one test I write a pcap from a list of Packets using a custom layer.
Scapy crashes in https://github.com/secdev/scapy/blob/v2.4.5/scapy/fields.py#L261:
```
    def do_copy(self, x):
        # type: (I) -> I
        if hasattr(x, "copy"):
>           return x.copy()  # type: ignore
E           TypeError: copy() missing 1 required positional argument: 'self'

../.local/lib/python3.8/site-packages/scapy/fields.py:261: TypeError
```

I'm not entirely sure how it gets into that situation, but my guess would be that this is a regression from https://github.com/secdev/scapy/pull/3365

### Scapy version

2.4.5

### Python version

3.8

### Operating system

Linux 5.4.0

### How to reproduce

Will look closer at this next week, hopefully I can give a simple example to reproduce.

<details><summary>IPython session showing the bug</summary>

```
In [12]: packets = rdpcap("path_to_SOMEIP_packets.pcap")

In [13]: packets
Out[13]: <sensor_status_pdu_packets.pcap: TCP:0 UDP:11 ICMP:0 Other:0>

In [14]: with BytesIO() as in_mem_file:
    ...:     writer = PcapWriter(in_mem_file)
    ...:     writer.write_header(None)
    ...:     writer.write(packets)
    ...:
WARNING: PcapWriter: unknown LL type for NoneType. Using type 1 (Ethernet)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-2c9a8db4b413> in <module>
      2     writer = PcapWriter(in_mem_file)
      3     writer.write_header(None)
----> 4     writer.write(packets)
      5

~/.local/lib/python3.8/site-packages/scapy/utils.py in write(self, pkt)
   1736             # Import here to avoid circular dependency
   1737             from scapy.supersocket import IterSocket
-> 1738             for p in IterSocket(pkt).iter:
   1739                 if not self.header_present:
   1740                     self.write_header(p)

~/.local/lib/python3.8/site-packages/scapy/supersocket.py in <genexpr>(.0)
    522                 self.iter = iter(obj)
    523             else:
--> 524                 self.iter = (y for x in obj for y in x)
    525         else:
    526             self.iter = obj.__iter__()

~/.local/lib/python3.8/site-packages/scapy/packet.py in loop(todo, done, self)
   1100                     # their sent_time attribute for sending purpose
   1101                     share_time = True
-> 1102                 for payl in payloads:
   1103                     # Let's make sure subpackets are consistent
   1104                     done2 = done.copy()

~/.local/lib/python3.8/site-packages/scapy/packet.py in loop(todo, done, self)
   1100                     # their sent_time attribute for sending purpose
   1101                     share_time = True
-> 1102                 for payl in payloads:
   1103                     # Let's make sure subpackets are consistent
   1104                     done2 = done.copy()

~/.local/lib/python3.8/site-packages/scapy/packet.py in loop(todo, done, self)
   1100                     # their sent_time attribute for sending purpose
   1101                     share_time = True
-> 1102                 for payl in payloads:
   1103                     # Let's make sure subpackets are consistent
   1104                     done2 = done.copy()

~/.local/lib/python3.8/site-packages/scapy/packet.py in loop(todo, done, self)
   1100                     # their sent_time attribute for sending purpose
   1101                     share_time = True
-> 1102                 for payl in payloads:
   1103                     # Let's make sure subpackets are consistent
   1104                     done2 = done.copy()

~/.local/lib/python3.8/site-packages/scapy/packet.py in loop(todo, done, self)
   1100                     # their sent_time attribute for sending purpose
   1101                     share_time = True
-> 1102                 for payl in payloads:
   1103                     # Let's make sure subpackets are consistent
   1104                     done2 = done.copy()

~/.local/lib/python3.8/site-packages/scapy/packet.py in loop(todo, done, self)
   1106                         if isinstance(done2[k], VolatileValue):
   1107                             done2[k] = done2[k]._fix()
-> 1108                     pkt = self.clone_with(payload=payl, share_time=share_time,
   1109                                           **done2)
   1110                     yield pkt

~/.local/lib/python3.8/site-packages/scapy/packet.py in clone_with(self, payload, share_time, **kargs)
   1052         pkt.explicit = 1
   1053         pkt.fields = kargs
-> 1054         pkt.default_fields = self.copy_fields_dict(self.default_fields)
   1055         pkt.overloaded_fields = self.overloaded_fields.copy()
   1056         pkt.time = self.time

~/.local/lib/python3.8/site-packages/scapy/packet.py in copy_fields_dict(self, fields)
    613         if fields is None:
    614             return None
--> 615         return {fname: self.copy_field_value(fname, fval)
    616                 for fname, fval in six.iteritems(fields)}
    617

~/.local/lib/python3.8/site-packages/scapy/packet.py in <dictcomp>(.0)
    613         if fields is None:
    614             return None
--> 615         return {fname: self.copy_field_value(fname, fval)
    616                 for fname, fval in six.iteritems(fields)}
    617

~/.local/lib/python3.8/site-packages/scapy/packet.py in copy_field_value(self, fieldname, value)
    607     def copy_field_value(self, fieldname, value):
    608         # type: (str, Any) -> Any
--> 609         return self.get_field(fieldname).do_copy(value)
    610
    611     def copy_fields_dict(self, fields):

~/.local/lib/python3.8/site-packages/scapy/fields.py in do_copy(self, x)
    259         # type: (I) -> I
    260         if hasattr(x, "copy"):
--> 261             return x.copy()  # type: ignore
    262         if isinstance(x, list):
    263             x = x[:]  # type: ignore

TypeError: copy() missing 1 required positional argument: 'self'
```
</details>

**Comment by gpotter2** [comment]
Thanks for the report, however this is already fixed on master !

**Comment by lalten** [comment]
Nice, thanks! Just found it: https://github.com/secdev/scapy/commit/aabf4b56f01fa22e039f6cd69e8058e0648b38e0 :)
